# Site settings
title: "Resumes"
description: "A resume template for Jekyll and GitHub Pages sites."

url: http://cv.gehtnicht.at
baseurl: ''

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
